- name: install libvirt
  yum:
    name:
      - libvirt-client
      - libvirt-daemon
      - qemu-kvm
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-kvm
      - virt-install
      - bridge-utils
      - rsync
      - virt-viewer
      - python-lxml # used by community.libvirt module
    state: present

- name: Enable and start libvirtd
  service:
    name: libvirtd
    state: started
    enabled: true

- name: create libvirt default pool directory
  file:
    path: "{{ libvirt_image_dir }}"
    owner: root
    group: root
    mode: 755
    state: directory

#- name: initialize libvirt default pool
- name: define libvirt default pool
  community.libvirt.virt_pool:
    name: default
    command: define
    xml: |
      <pool type='dir'>
       <name>default</name>
       <target>
         <path>{{ libvirt_image_dir }}</path>
         <permissions>
           <mode>0755</mode>
           <owner>0</owner>
           <group>0</group>
           <label>system_u:object_r:unlabeled_t:s0</label>
         </permissions>
        </target>
      </pool>

#- name: build libvirt default pool
#  community.libvirt.virt_pool:
#    name: default
#    command: build

#- name: create libvirt default pool
#  community.libvirt.virt_pool:
#    name: default
#    command: create

- name: activate libvirt default pool
  community.libvirt.virt_pool:
    name: default
    state: active
    autostart: yes

- name: autostart libvirt default pool
  community.libvirt.virt_pool:
    name: default
    autostart: yes

- name: define libvirt default net
  community.libvirt.virt_net:
    name: default
    command: define
    xml: |
      <network>
        <name>default</name>
        <uuid>9d391665-f52e-4379-94f6-98fc2881bde3</uuid>
        <forward mode='nat'>
          <nat>
            <port start='1024' end='65535'/>
          </nat>
        </forward>
        <bridge name='virbr0' stp='on' delay='0'/>
        <mac address='52:54:00:a8:55:a1'/>
        <ip address='192.168.122.1' netmask='255.255.255.0'>
          <dhcp>
            <range start='192.168.122.2' end='192.168.122.254'/>
          </dhcp>
        </ip>
      </network>

- name: start libvirt default net
  community.libvirt.virt_net:
    name: default
    state: active
    autostart: yes

- name: autostart libvirt default net
  community.libvirt.virt_net:
    name: default
    autostart: yes

#- name: enable IP forwarding
- name: enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
